"
This is an exception explicitly declared as being thrown by a method.
"
Trait {
	#name : #FmxNGTDeclaredException,
	#category : #'FmxNG-Traits-Traits'
}

{ #category : #meta }
FmxNGTDeclaredException classSide >> annotation [

	<generated>
	<ignoreInTraitUsers>
	<MSEClass: #TDeclaredException super: #Trait>
	<generated>
	<package: #'FmxNG-Traits'>
	^self
]

{ #category : #generator }
FmxNGTDeclaredException classSide >> generatedSlotNames [
	<generated>
	^ #(definingEntity)
]

{ #category : #generator }
FmxNGTDeclaredException classSide >> generatedTraitNames [
	<generated>
	^ #()
]

{ #category : #accessing }
FmxNGTDeclaredException >> definingEntity [

	<generated>
	^ definingEntity
]

{ #category : #accessing }
FmxNGTDeclaredException >> definingEntity: anObject [

	<generated>
	definingEntity := anObject

]
