accessing
signaledException: anObject
	signaledException := anObject