accessing
exceptionHandler: anObject
	exceptionHandler := anObject