public
handleException: anException with: anObject
	^ self handleException: anException do: [ anObject ]